
- name: Add Virtualbox GPG key
  apt_key: url=https://www.virtualbox.org/download/oracle_vbox_2016.asc

- name: Add Virtualbox APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ansible_distribution_release}} contrib

- name: Install Virtualbox packages
  apt:
    name: "{{ virtualbox_packages }}"
    state: present
  vars:
    virtualbox_packages:
      - virtualbox-6.1

- name: Change directory permission
  file:
    path:  "{{ item }}"
    owner: "root"
    group: "root"
  loop:
    - "/usr"
    - "/usr/lib"

- name: Check if java is installed on environment
  shell: "VBoxManage list extpacks | grep 'Extension Packs: 0'"
  ignore_errors: yes
  register: install_extpack

- name: Download Oracle VM Extension Pack
  get_url:
    url: "https://download.virtualbox.org/virtualbox/6.1.16/Oracle_VM_VirtualBox_Extension_Pack-6.1.16.vbox-extpack"
    dest: ./Oracle_VM_VirtualBox_Extension_Pack-6.1.16.vbox-extpack
    mode: '0440'
  when: install_extpack.stdout != ""

- name: Install Oracle VM Extension Pack
  shell: "echo 'y' | sudo VBoxManage extpack install Oracle_VM_VirtualBox_Extension_Pack-5.2.0.vbox-extpack"
  when: install_extpack.stdout != ""